# Model Architecture
model:
  use_concat: True
  max_seq_length: 95
  max_nmr_length: 190
  max_memory_length: 32
  embed_dim: 2048         # Direct embedding dimension
  width_basis: 13        # Base width for muP scaling calculations
  num_heads: 4
  num_layers: 8
  dropout: 0.0
  resample_size: 1000
  use_stablemax: True

# Training Parameters with muP settings
training:
  batch_size: 32
  test_batch_size: 1
  num_epochs: 10
  d1_horizon: 1000        # Original horizon where best LR was found
  best_d1_lr: 7.5e-4      # Best learning rate at d1 horizon
  min_learning_rate: 1.0e-5
  weight_decay: 0.1
  validation_frequency: 100
  logging_frequency: 10
  save_frequency: 1000
  save_model_frequency: 1000
  greedy_decode_frequency: 1000

# Optimizer Configuration
optimizer:
  type: adamw            # Using standard AdamW with muP
  adamw:
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.01
    caution: false

# Scheduler
scheduler:
  type: cosine
  warmup_steps: 100

# Data
data:
  use_parquet: False
  data_dir: "data_extraction/multimodal_spectroscopic_dataset"
  binary_dir: "preprocessed_binaries"
  test_size: 20
  val_size: 0.001
  preprocessed: False

# Logging
wandb:
  project: "smiles-generation-mup"
  base_run_name: "smiles_gen_mup"
  log_examples: true 