# Model Architecture
model:
  use_concat: True
  max_seq_length: 80
  embed_dim: 1024
  num_heads: 8
  num_layers: 6
  dropout: 0.1
  resample_size: 1000

# Training Parameters
training:
  batch_size: 32
  test_batch_size: 1
  num_epochs: 1
  learning_rate: 1.0e-4
  min_learning_rate: 1.0e-5
  validation_frequency: 50
  logging_frequency: 10
  save_frequency: 1000
  muon_lr: 0.02
  muon_momentum: 0.95
  muon_nesterov: true
  muon_ns_steps: 5
  adamw_betas: [0.9, 0.999]
  adamw_eps: 1.0e-8
  weight_decay: 0.01

# Scheduler
scheduler:
  warmup_steps: 100
  T0: 5
  T_mult: 2

# Data
data:
  use_parquet: False
  data_dir: "data_extraction/multimodal_spectroscopic_dataset"
  binary_dir: "preprocessed_binaries"
  test_size: 20
  val_size: 0.001
  preprocessed: True

# Logging
wandb:
  project: "smiles-generation"
  base_run_name: "smiles_gen"
  log_examples: true 